steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
      if [ $BRANCH_NAME == "dev" ]
      then
      echo "you are on the dev branch and will build your infrastructure in the dev workspace"
      else
      echo "you are on a different branch and will build your infrastructure in the default workspace"
      fi

# [START get-creds]
- id: 'get-creds'
  name: 'google/cloud-sdk'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      gcloud secrets versions access latest --secret=project_creds > project_creds.json
      mv project_creds.json modules/
      cd modules/
# [END get-creds]

# [START tf-init]
- id: 'tf init'
  name: 'hashicorp/terraform:0.13.6'
  entrypoint: 'sh'
  dir: 'modules/'
  args: 
  - '-c'
  - |
      terraform init
# [END tf-init]

# [START tf-fmt]
- id: 'tf fmt'
  name: 'hashicorp/terraform:0.13.6'
  entrypoint: 'sh'
  dir: 'modules/'
  args: 
  - '-c'
  - |
      echo "Terraform format"
      terraform fmt
# [END tf-fmt]

# [START tf-validate]
- id: 'tf validate'
  name: 'hashicorp/terraform:0.13.6'
  entrypoint: 'sh'
  dir: 'modules/'
  args: 
  - '-c'
  - |
      echo "Terraform validate"
      terraform validate
# [END tf-validate]

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:0.13.6'
  entrypoint: 'sh'
  dir: 'modules/'
  args: 
  - '-c'
  - | 
      if [ $BRANCH_NAME == "dev" ]
      then
      terraform workspace select dev
      else
      terraform workspace select default
      fi
      terraform workspace list
      terraform plan -var-file=myproject.tfvars
# [END tf-plan]

# [START tf-destroy]
- id: 'tf destory'
  name: 'hashicorp/terraform:0.13.6'
  entrypoint: 'sh'
  dir: 'modules/'
  args: 
  - '-c'
  - | 
      terraform workspace list
      terraform destroy --auto-approve -var-file=myproject.tfvars
# [END tf-destory]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:0.13.6'
  entrypoint: 'sh'
  dir: 'modules/'
  args: 
  - '-c'
  - | 
      terraform workspace list
      terraform apply --auto-approve -var-file=myproject.tfvars
# [END tf-apply]      